name: "Build NanoS"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"

  build_package_nanos:
    needs: configure
    runs-on: ubuntu-latest
    container:
      image: zondax/builder-bolos:latest
      options: --user ${{ needs.configure.outputs.uid_gid }}
    env:
      BOLOS_SDK: ${{ github.workspace }}/deps/nanos-secure-sdk
      BOLOS_ENV: /opt/bolos
      HOME: /home/zondax_circle
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install deps
        # With setuptools 66, the versions of all packages visible in the Python environment must obey PEP440
        # And there are some packages that don't conform to PEP440 so using setuptools@65.x for now
        # BUG: https://bugs.launchpad.net/ubuntu/+source/distro-info/+bug/2003583
        run: |
          pip install --upgrade --user setuptools==65.7.0
          pip install ledgerblue

      - name: Build NanoS
        shell: bash -l {0}
        run: |
          source $HOME/.cargo/env
          make
          mv ./app/pkg/installer_s.sh ./app/pkg/installer_nanos.sh

      - name: Set tag
        id: nanos
        run: echo ::set-output name=tag_name::$(./app/pkg/installer_nanos.sh version)
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          files: ./app/pkg/installer_nanos.sh
          tag_name: ${{ steps.nanos.outputs.tag_name }}
          draft: false
          prerelease: false